# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SaveTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveChanges(object):
    def setupUi(self, SaveChanges):
        SaveChanges.setObjectName("SaveChanges")
        SaveChanges.resize(519, 104)
        SaveChanges.setMinimumSize(QtCore.QSize(0, 0))
        SaveChanges.setMaximumSize(QtCore.QSize(1000, 1000))
        self.centralwidget = QtWidgets.QWidget(SaveChanges)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 325, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(260, 50, 195, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        SaveChanges.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SaveChanges)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 26))
        self.menubar.setObjectName("menubar")
        SaveChanges.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SaveChanges)
        self.statusbar.setObjectName("statusbar")
        SaveChanges.setStatusBar(self.statusbar)

        self.retranslateUi(SaveChanges)
        QtCore.QMetaObject.connectSlotsByName(SaveChanges)

    def retranslateUi(self, SaveChanges):
        _translate = QtCore.QCoreApplication.translate
        SaveChanges.setWindowTitle(_translate("SaveChanges", "Save Changes?"))
        self.label.setText(_translate("SaveChanges", "Would You Like To Save X Changes?"))
        self.pushButton.setText(_translate("SaveChanges", "OK"))
        self.pushButton_2.setText(_translate("SaveChanges", "Cancel"))
